app:
  build: .
  command: python3 main.py
  ports:
    - "5002:5000"
  links:
    - db

db:
  image: postgres
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: northwind
  ports:
      - 5436:5432
  restart: always

